version: '3.3'
services:
  tyk-hugo:
    image: klakegg/hugo:latest-ext
    container_name: tyk-hugo

    environment:
      - HUGO_BIND=0.0.0.0

    ports:
      - 1313:1313

    entrypoint: ["hugo", "server", "--theme=tykio", "--buildDrafts"]

    volumes:
    - ./tyk-docs:/src
