name: Stable branch update
on:
  push:
    branches:
      - main
      - master
      - release-*

jobs:
  stable:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release-4.3'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Update branch
        run: |
          git checkout -b stable
          git push origin -f stable

